### ISSUE TITLE
SELECT * 

### ISSUE THREAD

**Issue by yassienAbdillahi** [fac25/week4-karwan-manoela-sumithra-suraj#57]
In the my-howdies.js file the get_my_howdies sql query uses ```SELECT *```. 

_"It’s tempting to use SELECT * to list every column for each row, however it’s a good idea to list just the ones you need. In future this table may have many more columns added that this particular feature does not need (and they could be very large, or secret), and you would end up returning them all without meaning to"_ - from the [database workshop](https://learn.foundersandcoders.com/learn/database/)

**Comment by SurPun** [comment]
Thank you Yassien 🤩, we have fixed it on commit 5e9bfc611818e4c5b966365997f5b58fb4fb01e0
